# Generated by Django 4.2.28 on 2026-02-09 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom complet', max_length=100)),
                ('email', models.EmailField(help_text='Email de contact', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20)),
                ('appointment_type', models.CharField(choices=[('formation', 'Formation'), ('livrables', 'Livrables')], max_length=20)),
                ('appointment_date', models.DateField(help_text='Date du rendez-vous')),
                ('appointment_time', models.TimeField(help_text='Heure du rendez-vous')),
                ('duration_hours', models.IntegerField(default=1, help_text='Durée en heures')),
                ('subject', models.CharField(blank=True, help_text='Sujet du rendez-vous', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notes ou demandes spéciales')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['appointment_date', 'appointment_time'],
                'unique_together': {('appointment_type', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
